---
- name: Create docker group
  group: name=docker state=present

- name: Install docker
  yum: name=docker state=present
  notify: restart docker

- name: Ensure docker is enabled
  service: name=docker enabled=yes

- name: Ensure techops build requirements are installed
  yum: name={{ item }} state=present
  with_items:
  - gcc
  - python2-pip
  - python-devel

- name: Install ansible and docker-py
  pip: name={{ item.name }} version={{ item.version }}
  with_items: "{{ pip_packages }}"

- include: config.yml
